name: Build Sealos Offline Packages
on: [workflow_dispatch] # 允许手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download and Install Sealos
        run: |
          wget https://github.com/labring/sealos/releases/download/v5.1.1/sealos_5.1.1_linux_amd64.tar.gz
          tar zxvf sealos_5.1.1_linux_amd64.tar.gz sealos
          chmod +x sealos
          sudo mv sealos /usr/local/bin/

      - name: Pull and Save Images
        run: |
          mkdir output
          # 在 sealos 命令前加上 sudo 提权
          sudo sealos pull labring/kubernetes:v1.30.0
          sudo sealos pull labring/calico:v3.27.3
          sudo sealos save -o output/k8s-v1.30.0.tar labring/kubernetes:v1.30.0
          sudo sealos save -o output/calico-v3.27.3.tar labring/calico:v3.27.3
          
          # 修改文件夹权限，防止下一步上传时由于是 root 创建的文件而导致没有读取权限
          sudo chmod -R 777 output/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sealos-offline-packages
          path: output/*.tar
